steps:
  - name: install
    image: gittan/node:22
    run: corepack enable && pnpm install --frozen-lockfile
    cache:
      - node_modules

  - name: check
    image: gittan/node:22
    run: corepack enable && pnpm check
    needs: [install]

  - name: build
    image: gittan/node:22
    run: corepack enable && pnpm build
    needs: [install]

gated:
  - main
